apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-oneroster-rest-provider
spec:
  env:
    - name: server.servlet.context-path
      value: /mrfylke/ims/oneroster/v1p1
    - name: oneroster.access-control
      value: 'true'
    - name: oneroster.clients.itslearning.name
      value: oneroster_client_itslearning
    - name: oneroster.clients.itslearning.id
      value: 1df4c371-f4c4-48b0-a6b4-3f9183472720
    - name: oneroster.user-factory
      value: nin
    - name: oneroster.class-factory
      value: mrfylke
    - name: oneroster.contact-teacher-groups
      value: 'false'
    - name: oneroster.parents
      value: 'false'
    - name: oneroster.org.sourced-id
      value: '944183779'
    - name: oneroster.org.name
      value: Møre og Romsdal fylkeskommune
    - name: oneroster.org.identifier
      value: '944183779'
    - name: fint.component.education.registration.1.id
      value: mrfylke
    - name: fint.component.administration.registration.1.id
      value: mrfylke
    - name: spring.security.oauth2.client.registration.mrfylke.client-id
      valueFrom:
        secretKeyRef:
          name: fint-oneroster-rest-provider-op
          key: client-id
    - name: spring.security.oauth2.client.registration.mrfylke.client-secret
      valueFrom:
        secretKeyRef:
          name: fint-oneroster-rest-provider-op
          key: client-secret
    - name: spring.security.oauth2.client.registration.mrfylke.authorization-grant-type
      value: password
    - name: spring.security.oauth2.client.registration.mrfylke.scope
      value: fint-client
    - name: spring.security.oauth2.client.registration.mrfylke.provider
      value: fint
  onePassword:
    itemPath: vaults/aks-api-vault/items/oneroster-mrfylke
  url:
    hostname: api.felleskomponent.no
    basePath: /mrfylke/ims/oneroster/v1p1
  ingress:
    basePath: /mrfylke/ims/oneroster/v1p1