apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-oneroster-rest-provider
spec:
  env:
    - name: server.servlet.context-path
      value: /trondelagfylke/ims/oneroster/v1p1
    - name: oneroster.access-control
      value: "true"
    - name: oneroster.clients.itslearning.name
      value: oneroster_client_itslearning
    - name: oneroster.clients.itslearning.id
      value: 1df4c371-f4c4-48b0-a6b4-3f9183472720
    - name: oneroster.user-factory
      value: nin
    - name: oneroster.class-factory
      value: default
    - name: oneroster.contact-teacher-groups
      value: "true"
    - name: oneroster.parents
      value: "false"
    - name: oneroster.org.sourced-id
      value: "971045698"
    - name: oneroster.org.name
      value: Trøndelag fylkeskommune
    - name: oneroster.org.identifier
      value: "817920632"
    - name: fint.component.education.registration.1.id
      value: trondelagfylke
    - name: fint.component.administration.registration.1.id
      value: trondelagfylke
    - name: fint.component.education.registration.1.username
      valueFrom:
        secretKeyRef:
          name: fint-oneroster-rest-provider-op
          key: username
    - name: fint.component.education.registration.1.password
      valueFrom:
        secretKeyRef:
          name: fint-oneroster-rest-provider-op
          key: password
    - name: fint.component.administration.registration.1.username
      valueFrom:
        secretKeyRef:
          name: fint-oneroster-rest-provider-op
          key: username
    - name: fint.component.administration.registration.1.password
      valueFrom:
        secretKeyRef:
          name: fint-oneroster-rest-provider-op
          key: password
    - name: spring.security.oauth2.client.registration.trondelagfylke.client-id
      valueFrom:
        secretKeyRef:
          key: client-id
          name: fint-oneroster-rest-provider-op
    - name: spring.security.oauth2.client.registration.trondelagfylke.client-secret
      valueFrom:
        secretKeyRef:
          key: client-secret
          name: fint-oneroster-rest-provider-op
    - name: spring.security.oauth2.client.registration.trondelagfylke.authorization-grant-type
      value: password
    - name: spring.security.oauth2.client.registration.trondelagfylke.scope
      value: fint-client
    - name: spring.security.oauth2.client.registration.trondelagfylke.provider
      value: fint
    - name: JAVA_TOOL_OPTIONS
      value: "-Xmx3500m"
  ingress:
    basePath: /trondelagfylke/ims/oneroster/v1p1
    enabled: true
  onePassword:
    itemPath: vaults/aks-api-vault/items/oneroster-trondelagfylke
  orgId: trondelagfylke.no
  port: 8080
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  url:
    basePath: /trondelagfylke/ims/oneroster/v1p1
    hostname: api.felleskomponent.no
