apiVersion: v1
kind: Service
metadata:
  name: oneroster-rest-provider
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    io.kompose.service: oneroster-rest-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneroster-rest-provider
  labels:
    io.kompose.service: oneroster-rest-provider
spec:
  selector:
    matchLabels:
      io.kompose.service: oneroster-rest-provider
  template:
    metadata:
      labels:
        io.kompose.service: oneroster-rest-provider
    spec:
      containers:
        - name: oneroster-rest-provider
          image: fintlabs.azurecr.io/oneroster-rest-provider:build.4
          resources:
            limits:
              cpu: '2000m'
              memory: '4Gi'
            requests:
              cpu: '1000m'
              memory: '2Gi'
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /ims/oneroster/v1p1/actuator/health
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: -XX:+ExitOnOutOfMemoryError -Xmx3G