spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://idp.felleskomponent.no/nidp/oauth/nam/keys
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
