oneroster:
  org:
    sourced-id:
    name:
    identifier:
  user-factory:
  class-factory:
  access-control:
  extract-username-from-feideupn:
  clients:
    1:
      id:
      name:
fint:
  component:
    education:
      registration:
        1:
          id:
          username:
          password:
      endpoint:
        # TODO: Had to change from prod to beta links for this to work during 4.0 migration
        # Verify that this is OK and maybe change back to prod links after 4.0 migration
        school: https://beta.felleskomponent.no/utdanning/utdanningsprogram/skole
        person: https://beta.felleskomponent.no/utdanning/elev/person
        student: https://beta.felleskomponent.no/utdanning/elev/elev
        student-relation: https://beta.felleskomponent.no/utdanning/elev/elevforhold
        teacher: https://beta.felleskomponent.no/utdanning/elev/skoleressurs
        teaching-relation: https://beta.felleskomponent.no/utdanning/elev/undervisningsforhold
        basis-group: https://beta.felleskomponent.no/utdanning/elev/klasse
        basis-group-membership: https://beta.felleskomponent.no/utdanning/elev/klassemedlemskap
        level: https://beta.felleskomponent.no/utdanning/utdanningsprogram/arstrinn
        teaching-group: https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe
        teaching-group-membership: https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppemedlemskap
        subject: https://beta.felleskomponent.no/utdanning/timeplan/fag
        contact-teacher-group: https://beta.felleskomponent.no/utdanning/elev/kontaktlarergruppe
        contact-teacher-group-membership: https://beta.felleskomponent.no/utdanning/elev/kontaktlarergruppemedlemskap
        term: https://beta.felleskomponent.no/utdanning/kodeverk/termin
        school-year: https://beta.felleskomponent.no/utdanning/kodeverk/skolear
    administration:
      registration:
        1:
          id:
          username:
          password:
      endpoint:
        person: https://beta.felleskomponent.no/administrasjon/personal/person
        personnel: https://beta.felleskomponent.no/administrasjon/personal/personalressurs

scheduling:
  initial-delay: 10000
  fixed-delay: 3600000
  cron: 0 0 0 * * *

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
spring:
  profiles:
    include:
      - oauth