oneroster:
  org:
    sourced-id:
    name:
    identifier:
  academic-session:
    school-year:
      sourced-id:
      begin-date:
      end-date:
      name:
    first-term:
      sourced-id:
      begin-date:
      end-date:
      name:
    second-term:
      sourced-id:
      begin-date:
      end-date:
      name:
fint:
  component:
    education:
      registration:
        1:
          id:
          username:
          password:
      endpoint:
        school:
        person:
        student:
        student-relation:
        teacher:
        teaching-relation:
        basis-group:
        level:
        teaching-group:
        subject:
    administration:
      registration:
        1:
          id:
          username:
          password:
      endpoint:
        person:
        personnel:

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
