oneroster:
  org:
    sourced-id:
    name:
    identifier:
  academic-session:
    school-year:
      sourced-id:
      begin-date:
      end-date:
      name:
    first-term:
      sourced-id:
      begin-date:
      end-date:
      name:
    second-term:
      sourced-id:
      begin-date:
      end-date:
      name:
fint:
  component:
    education:
      registration:
        1:
          id:
          username:
          password:
      endpoint:
        school:
        person:
        student:
        student-relation:
        teacher:
        teaching-relation:
        basis-group:
        level:
        teaching-group:
        subject:
    administration:
      registration:
        1:
          id:
          username:
          password:
      endpoint:
        person:
        personnel:

spring:
  security:
    oauth2:
      client:
        registration:
          pwf-education:
            client-id:
            client-secret:
            authorization-grant-type: password
            scope: fint-client
            provider: fint
          pwf-administration:
            client-id:
            client-secret:
            authorization-grant-type: password
            scope: fint-client
            provider: fint
        provider:
          fint:
            token-uri:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  servlet:
    context-path: /ims/oneroster/v1p1