fint:
  organisation:
    registration: pwf
    sourcedId: 1234567890
    name: play-with-fint
    identifier: 1234567890
    school-year:
      begin-date: 2019-08-01
      end-date: 2020-07-31
      name: Skoleåret 2019/2020
      first-term:
        begin-date: 2019-08-01
        end-date: 2019-12-31
        name: 1. termin 2019/2020
      second-term:
        begin-date: 2020-01-01
        end-date: 2020-07-31
        name: 2. termin 2019/2020
    username: abc
    password: def
    environment: https://play-with-fint.felleskomponent.no

spring:
  security:
    oauth2:
      client:
        registration:
          pwf:
            client-id: abc
            client-secret: def
            authorization-grant-type: password
            scope: fint-client
            provider: fint
        provider:
          fint:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  servlet:
    context-path: /ims/oneroster/v1p1


