oneroster:
  org:
    sourced-id:
    name:
    identifier:
  user-factory:
  class-factory:
  access-control:
  extract-username-from-feideupn:
  clients:
    1:
      id:
      name:
fint:
  component:
    education:
      registration:
        1:
          id:
          username:
          password:
      endpoint:
        school:
        person:
        student:
        student-relation:
        teacher:
        teaching-relation:
        basis-group:
        level:
        teaching-group:
        subject:
        contact-teacher-group:
        term:
        school-year:
    administration:
      registration:
        1:
          id:
          username:
          password:
      endpoint:
        person:
        personnel:

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus