apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-oneroster-rest-provider
spec:
  env:
    - name: server.servlet.context-path
      value: /innlandet/ims/oneroster/v1p1
    - name: oneroster.access-control
      value: 'true'
    - name: oneroster.clients.itslearning.name
      value: oneroster_client_itslearning
    - name: oneroster.clients.itslearning.id
      value: 1df4c371-f4c4-48b0-a6b4-3f9183472720
    - name: oneroster.user-factory
      value: nin
    - name: oneroster.class-factory
      value: default
    - name: oneroster.contact-teacher-groups
      value: 'true'
    - name: oneroster.parents
      value: 'false'
    - name: oneroster.org.sourced-id
      value: '920717152'
    - name: oneroster.org.name
      value: Innlandet fylkeskommune
    - name: oneroster.org.identifier
      value: '920717152'
    - name: fint.component.education.registration.1.id
      value: innlandet
    - name: fint.component.administration.registration.1.id
      value: innlandet
    - name: spring.security.oauth2.client.registration.innlandet.client-id
      valueFrom:
        secretKeyRef:
          key: client-id
          name: oneroster-rest-provider-op
    - name: spring.security.oauth2.client.registration.innlandet.client-secret
      valueFrom:
        secretKeyRef:
          key: client-secret
          name: oneroster-rest-provider-op
    - name: spring.security.oauth2.client.registration.innlandet.authorization-grant-type
      value: password
    - name: spring.security.oauth2.client.registration.innlandet.scope
      value: fint-client
    - name: spring.security.oauth2.client.registration.innlandet.provider
      value: fint
  onePassword:
    itemPath: vaults/aks-api-vault/items/oneroster-innlandet
  url:
    hostname: api.felleskomponent.no
    basePath: /innlandet/ims/oneroster/v1p1
  ingress:
    basePath: /innlandet/ims/oneroster/v1p1