apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-oneroster-rest-provider
spec:
  env:
    - name: server.servlet.context-path
      value: /nfk/ims/oneroster/v1p1
    - name: oneroster.access-control
      value: 'true'
    - name: oneroster.clients.itslearning.name
      value: oneroster_client_itslearning
    - name: oneroster.clients.itslearning.id
      value: 1df4c371-f4c4-48b0-a6b4-3f9183472720
    - name: oneroster.user-factory
      value: nin
    - name: oneroster.class-factory
      value: default
    - name: oneroster.contact-teacher-groups
      value: 'true'
    - name: oneroster.parents
      value: 'true'
    - name: oneroster.org.sourced-id
      value: '964982953'
    - name: oneroster.org.name
      value: Nordland fylkeskommune
    - name: oneroster.org.identifier
      value: '964982953'
    - name: fint.component.education.registration.1.id
      value: nfk
    - name: fint.component.administration.registration.1.id
      value: nfk
    - name: spring.security.oauth2.client.registration.nfk.client-id
      value: ${client-id}
    - name: spring.security.oauth2.client.registration.nfk.client-secret
      value: ${client-secret}
    - name: spring.security.oauth2.client.registration.nfk.authorization-grant-type
      value: password
    - name: spring.security.oauth2.client.registration.nfk.scope
      value: fint-client
    - name: spring.security.oauth2.client.registration.nfk.provider
      value: fint
  onePassword:
    itemPath: vaults/aks-api-vault/items/oneroster-nfk
  url:
    hostname: api.felleskomponent.no
    basePath: /nfk/ims/oneroster/v1p1
  ingress:
    basePath: /nfk/ims/oneroster/v1p1