name: publish
on:
  repository_dispatch:
    types: [trigger-to-publish]
  
  workflow_dispatch:

env:
  REGISTRY_NAME: fintlabsacr
  ALPHA_CLUSTER_NAME: aks-alpha-fint-2021-11-18
  ALPHA_CLUSTER_RESOURCE_GROUP: rg-aks-alpha
  BETA_CLUSTER_NAME: aks-beta-fint-2021-11-23
  BETA_CLUSTER_RESOURCE_GROUP: rg-aks-beta
  API_CLUSTER_NAME: aks-api-fint-2022-02-08
  API_CLUSTER_RESOURCE_GROUP: rg-aks-api
  NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Get repo name
        id: get_repo
        run: echo ::set-output name=REPO::${GITHUB_REPOSITORY#*/}

      - name: Setup java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Connect to Azure Container Registry (ACR)
        uses: azure/docker-login@v3
        with:
           login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
           username: ${{ secrets.REGISTRY_USERNAME }}
           password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Gradle Setup
        uses: gradle/gradle-build-action@v2.8.0
        with:
          gradle-version: wrapper

      - name: Gradle build
        run: |
         ./gradlew build
         mkdir data
         cp ./build/libs/${GITHUB_REPOSITORY#*/}-*.jar ./data/app.jar
     
      - name: Container build and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{steps.get_repo.outputs.REPO}}:${{ github.sha }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{steps.get_repo.outputs.REPO}}:${{ github.sha }}

## Uncomment to trigger a deployment
## remember to set environment i deploy.yaml
      # - name: Start deployment workflow
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.GITHUBACTION_TOKEN}}
      #     event-type: trigger-to-deploy


