apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-oneroster-rest-provider
spec:
  template:
    spec:
      containers:
        - name: fint-oneroster-rest-provider
          readinessProbe:
            httpGet:
              path: /tffk/ims/oneroster/v1p1/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /tffk/ims/oneroster/v1p1/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 5
          envFrom:
            - secretRef:
                name: oneroster-rest-provider-op
          env:
            - name: server.servlet.context-path
              value: /tffk/ims/oneroster/v1p1
            - name: oneroster.access-control
              value: 'true'
            - name: oneroster.clients.itslearning.name
              value: oneroster_client_tffk
            - name: oneroster.clients.itslearning.id
              value: 4b67c3ba-59f8-456d-b086-f5b37821a873
            - name: oneroster.user-factory
              value: nin
            - name: oneroster.class-factory
              value: default
            - name: oneroster.contact-teacher-groups
              value: 'true'
            - name: oneroster.parents
              value: 'false'
            - name: oneroster.org.sourced-id
              value: '821227062'
            - name: oneroster.org.name
              value: Troms og Finnmark fylkeskommune
            - name: oneroster.org.identifier
              value: '821227062'
            - name: fint.component.education.registration.1.id
              value: tffk
            - name: fint.component.administration.registration.1.id
              value: tffk
            - name: spring.security.oauth2.client.registration.tffk.client-id
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: oneroster-rest-provider-op
            - name: spring.security.oauth2.client.registration.tffk.client-secret
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: oneroster-rest-provider-op
            - name: spring.security.oauth2.client.registration.tffk.authorization-grant-type
              value: password
            - name: spring.security.oauth2.client.registration.tffk.scope
              value: fint-client
            - name: spring.security.oauth2.client.registration.tffk.provider
              value: fint
